### PR TITLE
Fix SlewScopeToAltAz to use SlewToTopocentricCoordinates

### LINKED ISSUE #251: "Slew To Alt/Az" sends SlewToCoordinatesAsync instead of SlewToAltAzAsync
**Describe the bug**
In the Advanced Sequencer, the "Slew To Alt/Az" instruction sends a SlewToCoordinatesAsync (RA/Dec) command to the mount instead of the expected SlewToAltAzAsync command.

**To Reproduce**
1. Connect N.I.N.A. to ASCOM Device Hub (connected to a mount or Telescope Simulator).
2. Open Device Hub Activity Log (Tools -> View Activity Log).
3. Enable Telescope device and Commands Activity logging.
4. Run a sequence containing a Slew To Alt/Az instruction.
5. Observe the command received in the Device Hub log.

**Expected behavior**
The mount should receive a SlewToAltAzAsync command (if the driver supports it), consistent with the behavior of the "Manual Coordinates Alt/Az" feature in the Equipment -> Mount screen. Currently, it incorrectly sends SlewToCoordinatesAsync.

**Additional context**
In a fully automated remote observatory, I use the "Slew To Alt/Az" instruction during the initial power-on sequence to safely position the mount and to sync it with a plate solving.
Since the mount's RA/Dec coordinates may not yet be synchronized at startup, sending a SlewToCoordinatesAsync (RA/Dec) command causes the mount to calculate a slewing path based on invalid celestial data. This results in unpredictable and potentially dangerous movement. Using a true Alt/Az command is the only way to ensure the mount moves to a known physical orientation regardless of its current synchronization status.

Image

### PR DESCRIPTION
**Pull request by Mauro-Sturaro**
## 🚀 Purpose
Fixes #251

The "Slew To Alt/Az" sequence instruction was calling
`SlewToCoordinatesAsync(TopocentricCoordinates, token)` (marked [Obsolete]),
which converts Alt/Az to RA/Dec before slewing. This causes unpredictable
and potentially dangerous mount movement when the mount is not yet synced,
since the RA/Dec calculated from Alt/Az coordinates is invalid when the mount is not yet synchronized.

## 🧪 How Was It Tested?

Verified with ASCOM Device Hub activity log: the mount now receives a
SlewToAltAzAsync command instead of SlewToCoordinatesAsync.

## ✅ PR Checklist

- [X] All unit tests pass
- [ ] UI changes tested across Light, Dark, and Night themes (if applicable)
- [ ] Plugin API compatibility reviewed  
  - [X] No breaking changes to interfaces  
  - [X] No changes to method/class signatures (especially optional parameters)
- [X] `Changelog.md` updated (if applicable)
- [ ] [Documentation](https://github.com/isbeorn/nina.docs) updated (if applicable)

## 🔗 Related Issues

 Closes #251

### CODE REVIEW

File: NINA.Sequencer/SequenceItem/Telescope/SlewScopeToAltAz.cs [hunk 1]
```diff
@@ -131,7 +131,7 @@ public override async Task Execute(IProgress<ApplicationStatus> progress, Cancel
                 throw new SequenceEntityFailedException(Loc.Instance["LblTelescopeParkedWarning"]);
             }
             var stoppedGuiding = await guiderMediator.StopGuiding(token);
-            await telescopeMediator.SlewToCoordinatesAsync(Coordinates.Coordinates, token);
+            await telescopeMediator.SlewToTopocentricCoordinates(Coordinates.Coordinates, token);
```
Comment (isbeorn) [inline NINA.Sequencer/SequenceItem/Telescope/SlewScopeToAltAz.cs]: This will break backwards compatibility of existing sequences as it won't do sidereal tracking anymore.
Might be a better idea to have a toggle if sidereal tracking is desired or not (with default = on)

**Review by isbeorn — CHANGES_REQUESTED** [review]

File: NINA.Sequencer/SequenceItem/Telescope/SlewScopeToAltAz.cs (hunk 1 above)
Comment (Mauro-Sturaro) [reply NINA.Sequencer/SequenceItem/Telescope/SlewScopeToAltAz.cs]: Thank you for the explanation! I had not realized that both Slew To RA/Dec and Slew To Alt/Az instructions enable tracking before slewing.
However, I suspect that tracking being left on after an Alt/Az slew was not an intentional design decision, but rather an unintended side effect of using SlewToCoordinatesAsync in both cases — which is exactly the bug this PR is fixing.
That said, I fully understand that changing this behavior now could break existing sequences that rely on it, even if unintentionally. 
I'm not uset to work with the WPF UI but I will try to add a flag to choose behaviour.
I'm very busy so it will take some days.

Comment (isbeorn) [reply NINA.Sequencer/SequenceItem/Telescope/SlewScopeToAltAz.cs]: It was an intentional design decision and thus should be backwards compatible.

**Comment by Mauro-Sturaro** [comment]
I have implemented the tracking toggle as suggested, with default = true to preserve backwards compatibility. The checkbox is visible in the sequence instruction UI. Please re-review when you have a chance.

**Review by isbeorn — APPROVED** [review]
